### ISSUE TITLE
Switch all portfolios from Yarn to pnpm

### ISSUE THREAD

**Issue by karlhorky** [upleveled/next-portfolio-dev#67]

**Comment by ProchaLu** [comment]
Switched all portfolios to pnpm
- https://github.com/upleveled/portfolio-cms/pull/96
- https://github.com/upleveled/next-js-portfolio-web/pull/92
- https://github.com/upleveled/next-starter-peacock/pull/112
- https://github.com/upleveled/next-portfolio-dev/pull/72
